name: NetcallApp

options:
  bundleIdPrefix: com.example

targets:
  NetcallApp:
    type: application
    platform: iOS
    deploymentTarget: "17.0"

    settings:
      GENERATE_INFOPLIST_FILE: YES
      PRODUCT_BUNDLE_IDENTIFIER: com.Bonafons.Netcall
      SWIFT_VERSION: "6.2"

    sources:
      - Sources

    dependencies:
      - package: Netcall

packages:
  Netcall:
    path: ../../
